import type { FilterDefinition } from "../../types/filters";

export const filterDefinitions: FilterDefinition[] = [
  { key: "folder_path", label: "Folder Path", type: "enum", group: "general", apiParam: "folder_path" },
  { key: "container_format", label: "Container", type: "enum", group: "general", apiParam: "container_format" },
  { key: "title", label: "Title", type: "text", group: "general", apiParam: "title" },
  { key: "release_group", label: "Release Group", type: "enum", group: "general", apiParam: "release_group" },
  { key: "source", label: "Source", type: "enum", group: "general", apiParam: "source" },
  { key: "provider", label: "Provider", type: "enum", group: "general", apiParam: "provider" },
  { key: "year", label: "Year", type: "enum", group: "general", apiParam: "year" },
  { key: "hybrid", label: "Hybrid", type: "boolean", group: "general", apiParam: "hybrid" },
  { key: "invalid", label: "Invalid (No Tracks)", type: "boolean", group: "general", apiParam: "invalid" },
  { key: "overall_bitrate", label: "Overall Bitrate (Mbps)", type: "range", group: "general", apiParam: "overall_bitrate_min", apiParamMax: "overall_bitrate_max", multiplier: 1_000_000 },
  { key: "scanned_at", label: "Date Scanned", type: "date_range", group: "general", apiParam: "scanned_at_min", apiParamMax: "scanned_at_max" },
  { key: "file_modified_at", label: "Date Modified", type: "date_range", group: "general", apiParam: "file_modified_at_min", apiParamMax: "file_modified_at_max" },

  { key: "video.codec", label: "Video Codec", type: "enum", group: "video", apiParam: "video.codec" },
  { key: "video.bitrate", label: "Video Bitrate (Mbps)", type: "range", group: "video", apiParam: "video.bitrate_min", apiParamMax: "video.bitrate_max", multiplier: 1_000_000 },
  { key: "video.hdr10", label: "HDR10", type: "boolean", group: "video", apiParam: "video.hdr10" },
  { key: "video.dolby_vision", label: "Dolby Vision", type: "boolean", group: "video", apiParam: "video.dolby_vision" },
  { key: "video.dv_profile", label: "DV Profile", type: "enum", group: "video", apiParam: "video.dv_profile" },
  { key: "video.dv_layer", label: "DV Layer", type: "enum", group: "video", apiParam: "video.dv_layer" },
  { key: "video.hdr10_plus", label: "HDR10+", type: "boolean", group: "video", apiParam: "video.hdr10_plus" },
  { key: "video.resolution", label: "Resolution", type: "enum", group: "video", apiParam: "video.resolution" },
  { key: "video.width", label: "Width", type: "range", group: "video", apiParam: "video.width_min", apiParamMax: "video.width_max" },
  { key: "video.height", label: "Height", type: "range", group: "video", apiParam: "video.height_min", apiParamMax: "video.height_max" },
  { key: "video.language", label: "Video Language", type: "enum", group: "video", apiParam: "video.language" },
  { key: "video.display_aspect_ratio", label: "Aspect Ratio", type: "enum", group: "video", apiParam: "video.display_aspect_ratio" },
  { key: "video.bit_depth", label: "Bit Depth", type: "enum", group: "video", apiParam: "video.bit_depth" },
  { key: "video.color_primaries", label: "Color Primaries", type: "enum", group: "video", apiParam: "video.color_primaries" },
  { key: "video.transfer_characteristics", label: "Transfer", type: "enum", group: "video", apiParam: "video.transfer_characteristics" },
  { key: "video.encoding_library", label: "Encoder", type: "enum", group: "video", apiParam: "video.encoding_library" },
  { key: "video.scan_type", label: "Scan Type", type: "enum", group: "video", apiParam: "video.scan_type" },
  { key: "video.chroma_subsampling", label: "Chroma Subsampling", type: "enum", group: "video", apiParam: "video.chroma_subsampling" },

  { key: "audio.track_count", label: "Audio Track Count", type: "range", group: "audio", apiParam: "audio.track_count_min", apiParamMax: "audio.track_count_max" },
  { key: "audio.codec", label: "Audio Codec", type: "enum", group: "audio", apiParam: "audio.codec" },
  { key: "audio.bitrate", label: "Audio Bitrate (kbps)", type: "range", group: "audio", apiParam: "audio.bitrate_min", apiParamMax: "audio.bitrate_max", multiplier: 1_000 },
  { key: "audio.channel_layout", label: "Channel Layout", type: "enum", group: "audio", apiParam: "audio.channel_layout" },
  { key: "audio.language", label: "Audio Language", type: "enum", group: "audio", apiParam: "audio.language" },
  { key: "audio.is_default", label: "Default Track", type: "boolean", group: "audio", apiParam: "audio.is_default" },
  { key: "audio.is_original", label: "Original Language", type: "boolean", group: "audio", apiParam: "audio.is_original" },
  { key: "audio.is_atmos", label: "Atmos", type: "boolean", group: "audio", apiParam: "audio.is_atmos" },
  { key: "audio.is_commentary", label: "Commentary", type: "boolean", group: "audio", apiParam: "audio.is_commentary" },
  { key: "audio.sample_rate", label: "Sample Rate", type: "enum", group: "audio", apiParam: "audio.sample_rate" },
  { key: "audio.compression_mode", label: "Compression", type: "enum", group: "audio", apiParam: "audio.compression_mode" },

  { key: "subtitle.track_count", label: "Subtitle Track Count", type: "range", group: "subtitle", apiParam: "subtitle.track_count_min", apiParamMax: "subtitle.track_count_max" },
  { key: "subtitle.codec", label: "Subtitle Codec", type: "enum", group: "subtitle", apiParam: "subtitle.codec" },
  { key: "subtitle.language", label: "Subtitle Language", type: "enum", group: "subtitle", apiParam: "subtitle.language" },
  { key: "subtitle.is_forced", label: "Forced", type: "boolean", group: "subtitle", apiParam: "subtitle.is_forced" },
  { key: "subtitle.is_hearing_impaired", label: "Hearing Impaired", type: "boolean", group: "subtitle", apiParam: "subtitle.is_hearing_impaired" },
];
